#########################################################################

# This version generates random data for a given number of quarters.
# Different instances can be generated by changing the integer ("2") in
# the following command:

option randseed 2;

# PREAMBLE: Here we define sets and parameters

###########################################################
# With the following two parameters you can change the size
# of the instances

# Number of quarters
param NumQuarters := 12;

# Number of classes per quarter
param MaxClassesPerQuarter := 4;
###########################################################

# Set of quarters (simply numbered from 1 to NumQuarters)
set QUARTERS := {1..NumQuarters};

# Set of classes
set CLASSES := {1 .. NumQuarters*MaxClassesPerQuarter};

# Number of hours per week for each class
param hours{i in CLASSES} = max(round(100*Normal(10,5))/100,0)+2;

# Here we generate a random assignment to the quarters

# The following parameter determines what percentage of possible arcs
# that are connected.  The smaller the value, the fewer prerequisites

param threshold = 0.2;

param TempQuarter{i in CLASSES} = ceil(NumQuarters*Uniform(0,1));
param TempPair{i in CLASSES, j in CLASSES} = Uniform(0,1);
# Set of prerequisites:
set PREREQS = {i in CLASSES, j in CLASSES: TempQuarter[i] < TempQuarter[j] && TempPair[i,j]<threshold};

#########################################################################

# MODEL: Here we define variables, objective, and constraints

# Usually, you would write your model here, but because want to have the same
# model work with another preamble (that uses randomly generated data), we
# include the model from a different file:

include obj1_model.inc
